### ISSUE TITLE
Release 0.1 Tracker

### ISSUE THREAD

**Issue by mmcdermott** [mmcdermott/MEDS_transforms#35]
Bugs:
- [x] #142 

Release 0.0.1
- [x] #73 

Naming & Packaging & MEDS
- [x] #32

Interface

Transforms
- [x] #101
- [x] #58
- [x] #47
- [x] #51
- [x] #122
- [x] #127 

Extraction ETL
- [x] #34
- [x] #78 
- [x] https://github.com/mmcdermott/MEDS_transforms/issues/129
- [x] https://github.com/mmcdermott/MEDS_transforms/issues/125

Public Data Examples
- [x] #53
- [x] Finish validation of MIMIC-IV example with slurm parallelism and find reasonable parameters for same.
- [x] #31 

Documentation & Testing
- [x] Add comprehensive terminology document.
- [x] #15
- [x] Add documentation on how it connects with MEDS-torch / MEDS_pytorch_dataset.
- [x] #170
- [x] #100
